version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: prospectdb
      POSTGRES_USER: prospectuser
      POSTGRES_PASSWORD: prospectpass
    ports:
      - "5432:5432"

volumes:
  pgdata:
